[ClassVersion("1.0.0"), FriendlyName("xWebfarm")] 
class MSFT_xWebfarm : OMI_BaseResource
{
  [Key] string Name;
  [write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
  [write] bool Enabled;
}; 

