[ClassVersion("1.0.0"), FriendlyName("xIisMimeTypeMapping")] 
class MSFT_xIisMimeTypeMapping : OMI_BaseResource
{
  [Key, Description("The file extension to map")] string Extension;
  [Key, Description("The MIME type to map that extension")] string MimeType;
  [Key, Description("The full IIS path of where the MIME type will be added. Website name to begin then virtual directories or web applications to follow")] string IisFullPath;
  [Required, Description("Whether MIME type should be present or absent"),ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
};
