[ClassVersion("1.0.0")]
Class MSFT_xWebBindingInformation
{
    [write]UInt16 Port;
    [Write,ValueMap{"http", "https"},Values{"http", "https"}] string Protocol;
    [write]String IPAddress;
    [write]String HostName;
    [write]String CertificateThumbprint;
    [write,ValueMap{"My", "WebHosting"},Values{"My", "WebHosting"}] string CertificateStoreName;
    [write,ValueMap{"0","1","2","3"},Values{"0","1","2","3"}] string SSLFlags;
};


[ClassVersion("2.0.0"), FriendlyName("xWebsite")]
class MSFT_xWebsite : OMI_BaseResource
{
  [Key] string Name;
  [Required] string PhysicalPath;
  [write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
  [write,ValueMap{"Started","Stopped"},Values{"Started", "Stopped"}] string State;
  [write, EmbeddedInstance("MSFT_xWebBindingInformation"), Description("Hashtable containing binding information (Port, Protocol, IPAddress, HostName, CertificateThumbPrint, CertificateStore)")] string BindingInfo[];
  [write] string ApplicationPool;
  [read] string Id;
  [write, Description("The default pages for the website")] String DefaultPage[];
};


