
[ClassVersion("1.0.0.0"), FriendlyName("xWebApplication")]
class MSFT_xWebApplication : OMI_BaseResource
{
    [Key, Description("Name of website with which web application is associated")] string Website;
    [Key, Description("Name of web application")] string Name;
    [Required, Description("Web application pool for the web application")] string WebAppPool;
    [Required, Description("Physical path for the web application directory")] string PhysicalPath;
    [Write, Description("Whether web application should be present or absent"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
};




