[ClassVersion("1.0.0"), FriendlyName("xIisLogging")] 
class MSFT_xIisLogging : OMI_BaseResource
{
  [Key] string LogPath;
  [Required,ValueMap{"Date","Time","ClientIP","UserName","SiteName","ComputerName","ServerIP","Method","UriStem","UriQuery","HttpStatus","Win32Status","BytesSent","BytesRecv","TimeTaken","ServerPort","UserAgent","Cookie","Referer","ProtocolVersion","Host","HttpSubStatus"}] string LogFlags;
};
