ConvertFrom-StringData @'
    ErrorftpSiteDiscoveryFailure                     = Failure to get the requested ftpSite "{0}" information from the target machine.
    ErrorftpSiteCreationFailure                      = Failure to successfully create the ftpSite "{0}". Error: "{1}".
    ErrorftpSiteRemovalFailure                       = Failure to successfully remove the ftpSite "{0}". Error: "{1}".
    ErrorftpSiteStateFailure                         = Failure to successfully set the state of the website "{0}". Error: "{1}".
    ErrorServerCertHashFailure                       = No such cert with the hash of "{0}" exists under store "{1}".
    VerboseGetTargetAbsent                           = No ftpSite exists with this name.
    VerboseGetTargetPresent                          = A single ftpSite exists with this name.
    VerboseSetTargetftpSiteCreated                   = Successfully created ftpSite "{0}".
    VerboseSetTargetftpSiteRemoved                   = Successfully removed ftpSite "{0}".
    VerboseSetTargetAuthenticationInfoUpdated        = Successfully updated AuthenticationInfo on ftpSite "{0}".
    VerboseSetTargetAuthorizationInfoUpdated         = Successfully updated AuthorizationInfo on ftpSite "{0}".
    VerboseSetTargetUpdateAllowLocalDetailedErrors   = Successfully updated AllowLocalDetailedErrors on ftpSite "{0}".
    VerboseSetTargetUpdateBannerMessage              = Successfully updated Banner message on ftpSite "{0}".
    VerboseSetTargetUpdatedApplicationPool           = Successfully updated ApplicationPool on ftpSite "{0}".
    VerboseSetTargetUpdatedBindingInfo               = Successfully updated BindingInfo on ftpSite "{0}".
    VerboseSetTargetUpdateDirectoryBrowseFlags       = Successfully updated DirectoryBrowseFlags on ftpSite "{0}".
    VerboseSetTargetUpdateEndingDataChannelPort      = Successfully updated ending data channel port on ftpSite "{0}".
    VerboseSetTargetUpdateExitMessage                = Successfully updated Exit message on ftpSite "{0}".
    VerboseSetTargetUpdateExpandVariablesInMessages  = Successfully updated ExpandVariablesInMessages on ftpSite "{0}".
    VerboseSetTargetUpdateExternalIPaddress          = Successfully updated external firewall IP address on ftpSite "{0}".
    VerboseSetTargetUpdateGreetingMessage            = Successfully updated Greeting message on ftpSite "{0}".
    VerboseSetTargetUpdateLogFlags                   = Successfully updated LogFlags on ftpSite "{0}".
    VerboseSetTargetUpdateLoglocalTimeRollover       = Successfully updated LoglocalTimeRollover on ftpSite "{0}".
    VerboseSetTargetUpdateLogPath                    = Successfully updated LogPath on ftpSite "{0}".
    VerboseSetTargetUpdateLogPeriod                  = Successfully updated LogPeriod on ftpSite "{0}".
    VerboseSetTargetUpdateLogTruncateSize            = Successfully updated TruncateSize on ftpSite "{0}".
    VerboseSetTargetUpdateMaxClientsMessage          = Successfully updated MaxClients message on ftpSite "{0}".
    VerboseSetTargetUpdatedPhysicalPath              = Successfully updated PhysicalPath on ftpSite "{0}".
    VerboseSetTargetUpdatePhysicalPathAccessPassword = Successfully updated password for physical path access on ftpSite "{0}".
    VerboseSetTargetUpdatePhysicalPathAccessUsername = Successfully updated username for physical path access on ftpSite "{0}".
    VerboseSetTargetUpdatedState                     = Successfully updated State on ftpSite "{0}".
    VerboseSetTargetUpdateSslInfo                    = Successfully updated SslInfo on ftpSite "{0}".
    VerboseSetTargetUpdateStartingDataChannelPort    = Successfully updated starting data channel port on ftpSite "{0}".
    VerboseSetTargetUpdateSuppressDefaultBanner      = Successfully updated SuppressDefaultBanner on ftpSite "{0}".
    VerboseSetTargetUpdateUserIsolation              = Successfully updated UserIsolation on ftpSite "{0}".
    VerboseTestTargetFalseAllowLocalDetailedErrors   = AllowLocalDetailedErrors for ftpSite "{0}" does not match the desired state.
    VerboseTestTargetFalseApplicationPool            = Application Pool for ftpSite "{0}" does not match the desired state.
    VerboseTestTargetFalseAuthenticationInfo         = AuthenticationInfo for ftpSite "{0}" is not in the desired state.
    VerboseTestTargetFalseAuthorizationInfo          = AuthorizationInfo for ftpSite "{0}" is not in the desired state.
    VerboseTestTargetFalseBannerMessage              = BannerMessage for ftpSite "{0}" is not in the desired state.
    VerboseTestTargetFalseBindingInfo                = BindingInfo for ftpSite "{0}" is not in the desired state.
    VerboseTestTargetFalseDirectoryBrowseFlags       = DirectoryBrowseFlags for ftpSite "{0}" is not in the desired state.
    VerboseTestTargetFalseEndingDataChannelPort      = Ending data channel port for ftpSite "{0}" is not in the desired state.
    VerboseTestTargetFalseEnsure                     = The Ensure state for ftpSite "{0}" does not match the desired state.
    VerboseTestTargetFalseExitMessage                = ExitMessage for ftpSite "{0}" does not match the desired state.
    VerboseTestTargetFalseExpandVariablesInMessages  = ExpandVariablesInMessages for ftpSite "{0}" does not match the desired state.
    VerboseTestTargetFalseExternalIPaddress          = The external firewall IP address for ftpSite "{0}" does not match the desired state.
    VerboseTestTargetFalseGreetingMessage            = GreetingMessage for ftpSite "{0}" does not match the desired state.
    VerboseTestTargetFalseLogFlags                   = LogFlags for ftpSite "{0}" is not in the desired state.
    VerboseTestTargetFalseLoglocalTimeRollover       = LoglocalTimeRollover for ftpSite "{0}" is not in the desired state.
    VerboseTestTargetFalseLogPath                    = LogPath for ftpSite "{0}" is not in the desired state.
    VerboseTestTargetFalseLogPeriod                  = LogPeriod for ftpSite "{0}" is not in the desired state.
    VerboseTestTargetFalseLogTruncateSize            = LogTruncateSize for ftpSite "{0}" is not in the desired state.
    VerboseTestTargetFalseMaxClientsMessage          = MaxClientsMessage for ftpSite "{0}" is not in the desired state.
    VerboseTestTargetFalseSslInfo                    = SslInfo for ftpSite "{0}" is not in the desired state.
    VerboseTestTargetFalseStartingDataChannelPort    = Starting data channel port for ftpSite "{0}" is not in the desired state.
    VerboseTestTargetFalseState                      = The state of ftpSite "{0}" does not match the desired state.
    VerboseTestTargetFalseSuppressDefaultBanner      = SuppressDefaultBanner for ftpSite "{0}" is not in the desired state.
    VerboseTestTargetFalsePhysicalPath               = Physical Path of ftpSite "{0}" does not match the desired state.
    VerboseTestTargetFalsePhysicalPathAccessPassword = Password for physical path access of ftpSite "{0}" does not match the desired state.
    VerboseTestTargetFalsePhysicalPathAccessUsername = Username for physical path access of ftpSite "{0}" does not match the desired state.
    VerboseTestTargetFalseUserIsolation              = UserIsolation for ftpSite "{0}" is not in the desired state.
    VerboseTestTargetTrueResult                      = The target resource is already in the desired state. No action is required.
    VerboseTestTargetFalseResult                     = The target resource is not in the desired state.
    VerboseStartWebsite                              = Successfully started ftpSite "{0}".
    VerboseStopWebsite                               = Successfully stopped ftpSite "{0}".
    WarningLogPeriod                                 = LogTruncateSize is specified as an input so LogPeriod input will be ignored and set to "MaxSize" on Website "{0}".
'@
